apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  namespace: nok-cgnat
  name: cgnat-state
spec:
  clusterRef: cgnat-state
  enabled: true
  targetSelectors:
    - matchLabels:
        vendor: Nokia
        role: cgnat
  subscriptionRefs:
    - sros-nat-availability-on-change
  outputs:
    outputSelectors:
      - matchLabels:
          type: cgnat-state
    processorRefs:
      - oper-state-to-int
