apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: system-resource-alerts
  namespace: nok-cgnat
  labels:
    role: alert-rules # Must match the ruleSelector above
spec:
  groups:
  - name: system-usage
    rules:
    - alert: HighCpuUsage
      expr: state_system_cpu_summary_usage_cpu_usage > 12
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on {{ $labels.instance }}"
        description: "CPU usage is at {{ $value }}% (threshold 12%)"

    - alert: HighMemoryUsage
      expr: (state_system_memory_pools_summary_total_in_use / state_system_memory_pools_summary_available_memory) * 100 > 2
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High Memory usage on {{ $labels.instance }}"
        description: "Memory utilization is at {{ $value }}% (threshold 2%)"
