apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: nok-cgnat
  namespace: nok-cgnat
spec:
  replicas: 1
  alerting:
    alertmanagers:
    - namespace: nok-cgnat
      name: alertmanager-operated
      port: web
  ruleSelector:
    matchLabels:
      role: alert-rules      
  serviceAccountName: prometheus
  serviceMonitorSelector: {} 
  podMonitorSelector: {} 
  podMetadata:
    annotations:
      netopskube.io/bbm: "true"
      netopskube.io/prober: "http"
      netopskube.io/scheme: "http"
      netopskube.io/path: "/-/ready"
  resources:
    requests:
      memory: 400Mi
  externalUrl: /nok-cgnat/prometheus
  routePrefix: /