apiVersion: nok.dev/v1alpha1
kind: NetworkHostTarget
metadata:
  name: clab-sros-cgnat-lan3
  namespace: nok-cgnat
spec:
  address: 172.21.30.133
  hostname: clab-sros-cgnat-lan3
  commonLabels:
    role: host
