apiVersion: operator.gnmic.dev/v1alpha1
kind: Processor
metadata:
  namespace: nok-cgnat
  name: oper-state-to-int
spec:
  type: event-strings
  config:
    value-names:
      - ".*"
    transforms:
      - replace:
          apply-on: "value"
          old: "^true$"
          new: "1"
      - replace:
          apply-on: "value"
          old: "^false$"
          new: "0"
      - replace:
          apply-on: "value"
          old: "^unknown$"
          new: "1"
      - replace:
          apply-on: "value"
          old: "^up$"
          new: "2"
      - replace:
          apply-on: "value"
          old: "^down$"
          new: "3"
      - replace:
          apply-on: "value"
          old: "^transition$"
          new: "4"
      - replace:
          apply-on: "value"
          old: "^unavail$"
          new: "0"
      - replace:
          apply-on: "value"
          old: "^primary$"
          new: "1"
      - replace:
          apply-on: "value"
          old: "^backup$"
          new: "2"
      - replace:
          apply-on: "value"
          old: "^busy$"
          new: "3"
      - replace:
          apply-on: "value"
          old: "^in-service$"
          new: "2"
      - replace:
          apply-on: "value"
          old: "^out-of-service$"
          new: "3"
      - replace:
          apply-on: "value"
          old: "^inactive$"
          new: "1"
      - replace:
          apply-on: "value"
          old: "^needs-reset$"
          new: "3"
      - replace:
          apply-on: "value"
          old: "^resetting$"
          new: "4"
      - replace:
          apply-on: "value"
          old: "^initial-wait-for-peer$"
          new: "2"
      - replace:
          apply-on: "value"
          old: "^wait-for-peer$"
          new: "3"
      - replace:
          apply-on: "value"
          old: "^peer-timed-out$"
          new: "4"
      - replace:
          apply-on: "value"
          old: "^waiting-selection$"
          new: "1"
      - replace:
          apply-on: "value"
          old: "^negotiating$"
          new: "3"
