apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  namespace: nok-cgnat
  name: sros-system-performance
  labels:
    type: cgnat
spec:
  paths:
    - /state/system/cpu
    - /state/system/memory-pools
  mode: STREAM/SAMPLE
  encoding: JSON
  sampleInterval: 60s
  heartbeatInterval: 90s
